version: '2'
services:
  judge1:
     depends_on:
       - db
     build:
       context: .
     environment:
       JAR_FILE: judge-1.0-SNAPSHOT.jar
     ports:
       - 8080:8080
     volumes:
       - ./docker/volumes/deployment:/app:ro
     links:
       - db:db
  db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: judge
     hostname: localhost
     ports:
       - 3306:3306
volumes:
    db_data:
